### ISSUE TITLE
请升级vconsole到3.0版本

### ISSUE THREAD

**Issue by MarvinXu** [diamont1001/vconsole-webpack-plugin#10]
新版vconsole对手淘flexible布局做了适应，希望能升级
https://github.com/Tencent/vConsole/blob/dfb0478a1efc803e32a507dddaaf862a66b54dbe/src/core/core.js#L171

**Comment by diamont1001** [comment]
好了，@1.3.0 版本，但是不知道为什么，这边网络 publish 不了，有空再放上去

**Comment by MarvinXu** [comment]
赞~

**Comment by diamont1001** [comment]
done. @1.3.0
