### ISSUE TITLE
iOS 12 白屏 ResizeObserver 找不到

### ISSUE THREAD

**Issue by Nstd** [diamont1001/vconsole-webpack-plugin#102]
这个问题是因为ResizeObserver在iOS 12以下找不到，需要在初始化 vConsole 之前导入 对应的polyfill
https://github.com/Tencent/vConsole/issues/584
``` javascript
let ResizeObserver = require('resize-observer-polyfill').default

window.ResizeObserver = window.ResizeObserver || ResizeObserver
```

**Comment by idabaicai** [comment]
> ```js
> let ResizeObserver = require('resize-observer-polyfill').default
> ```

It's works for me!

**Comment by diamont1001** [comment]
v1.8.0 已修复

**Comment by nondanee** [comment]
打包后存在 es6 语法，应该用 `var ResizeObserver = ...` = =
