### ISSUE TITLE
entry 里应该排除webpack-dev-server

### ISSUE THREAD

**Issue by muuyao** [diamont1001/vconsole-webpack-plugin#11]
当使用 webpack-dev-server 启动时，entry里会包括webpack-dev-server相关路径，不应该插入vconsole

**Comment by diamont1001** [comment]
嗯嗯，现在使用option.filter可以过滤，我明天有空把它加到默认里去，非常感谢

**Comment by diamont1001** [comment]
好了，代码更新上去了，1.4.0，但是我这边 npm 抽风了，一直 publish 不上去，有空再弄吧

**Comment by diamont1001** [comment]
@1.4.0

done.
