### ISSUE TITLE
使用webpack-chain来加载插件应该比较好，这样就不需要enable属性了

### ISSUE THREAD

**Issue by jiankafei** [diamont1001/vconsole-webpack-plugin#14]
可以通过 webpack-chain 动态加载 vconsole-webpack-plugin，建议去掉 enable 属性

**Comment by diamont1001** [comment]
感谢建议！

不过，`webpack-chain` 毕竟是小部分人用到的，本插件肯定是需要优先适配官方（大部分人）的配置方法。

或者你贴一下你使用 `webpack-chain` 配置的关键代码我看看，能不能在现有的情况下做好兼容，谢谢！

**Comment by jiankafei** [comment]
```js
const baseConfig = require('./webpack.conf');
const Config = require('webpack-chain');
const yargs = require('yargs');
const merge = require('webpack-merge');
const vConsolePlugin = require('vconsole-webpack-plugin');

const config = new Config();
if (yargs.argv.debug) {
config
  .plugin(‘vconsole-webpack-plugin’)
  .use(vConsolePlugin, [{enable: true}]);
}
module.exports = merge(baseConfig, config.toString());

```

直接的webpack配置就用以上方式，可能会有错，就是个示例，vue-cli3中提供chainWebpack，就是使用的webpack-chain，直接使用即可

**Comment by diamont1001** [comment]
嗯，看你的配置，其实 `enable` 参数去掉的话也只是少了 `[{enable: true}]` 这一点配置而已，但是对官方的用法的同学就会很麻烦，所以衡量之下，还是保留 `enable` 参数更好。

感谢建议，感谢关注，有什么欢迎继续讨论。
