### ISSUE TITLE
请问vConsolePlugin如何兼容Android 5.0以下版本？

### ISSUE THREAD

**Issue by zhongmeizhi** [diamont1001/vconsole-webpack-plugin#17]
![image](https://user-images.githubusercontent.com/17895124/58849125-bda19380-86bb-11e9-954c-b155d656b28d.png)

**Comment by diamont1001** [comment]
噢，这个只是 [vConsole](https://github.com/Tencent/vConsole) 的一个webpack 上的插件，你说的这个兼容性的问题应该是 vConsole 的，建议到  [vConsole](https://github.com/Tencent/vConsole)  去提一下兼容性问题，谢谢 ^_^

**Comment by zhongmeizhi** [comment]
收到。谢谢提醒。
