### ISSUE TITLE
ios8 页面白屏

### ISSUE THREAD

**Issue by wangyajundev** [diamont1001/vconsole-webpack-plugin#18]
ios8 页面白屏

**Comment by diamont1001** [comment]
是 iphone 8 手机白屏吗，还是？

**Comment by wangyajundev** [comment]
页面不显示，vconsole图标显示了，但点击开后，只显示hide，其他都没有

**Comment by diamont1001** [comment]
vconsole图标显示，那代表本插件已经完成了 vconsole 的加载。
至于显示效果的bug，这个需要到 [vconsole](https://github.com/Tencent/vConsole/issues) 那边去提 bug 喔 ^_^
