### ISSUE TITLE
可否提供出vconsole的实例，因为需要destory

### ISSUE THREAD

**Issue by pangjunpeng** [diamont1001/vconsole-webpack-plugin#21]
我们的页面pc，移动端都有。但是在pc上时不想要vconsole，想把它destory掉，但是没有提供实例无法操作

**Comment by diamont1001** [comment]
感觉可以，我搞下

**Comment by diamont1001** [comment]
这几天休假了，在家里网络发布不了 npm

**Comment by diamont1001** [comment]
done.

see 1.5.0

```
window.vConsole
```

**Comment by pangjunpeng** [comment]
感谢大佬🌹

**Comment by pangjunpeng** [comment]
@diamont1001 感谢大佬的及时响应，试用了下可以实现效果。
但是由于我一开始思路有误，导致不是理想效果。因为他一开始还是会先初始化一遍，再destory，影响页面性能，而且会给控制台输出一堆信息

可否实现这样的功能
```
plugins: [
  // ...
  new vConsolePlugin({
      enable: devEnvConfig.debug === 'true',
      test(){
        const ua = navigator.userAgent
        return ua.match(/mobile/i)
      }
    }),
]
```
传入test函数（随便起的名字），在`vconsole-webpack-plugin/src/vconsole.js`文件内执行这个函数，根据结果是true/false来 判断是否`new vConsole`

**Comment by diamont1001** [comment]
你是想放到生产环境吗？

如果是测试环境的话，其实在PC端显示出来也没啥影响；
如果是生产环境的话，可以直接使用 vConsole，然后自己根据需求来 new。
