### ISSUE TITLE
webpack 如何配置插件

### ISSUE THREAD

**Issue by pangxieju** [diamont1001/vconsole-webpack-plugin#4]
按照 demo 配置了 webpack ，页面上没有出现 vconsole 按钮，请问如何配置。

**Comment by diamont1001** [comment]
直接按以下的配置方式也不行吗？
```js
// 引入插件
var vConsolePlugin = require('vconsole-webpack-plugin'); 

module.exports = {
    ...

    plugins: [
        new vConsolePlugin({
            enable: true // 发布代码前记得改回 false
        }),
        ...
    ]
    ...
}
```

确实搞不定的话，可以贴上配置代码来看看，或者方便的话也可以把最小可复现代码打包发我邮箱我看看

jingren.cjr@alibaba-inc.com

**Comment by pangxieju** [comment]
不好意思，由于网络问题刚看到信息。
非常感谢你的回答。
这个问题已经解决了。
原因 webpack 缓存，配置无法生效。

**Comment by diamont1001** [comment]
好的，解决了就好

**Comment by SilasDong** [comment]
我也出现这个问题，集成了没有报错，但是不现实绿色按钮，请问您是怎么决解的

**Comment by SilasDong** [comment]
// webpack.dev.conf
'use strict'
const utils = require('./utils')
const webpack = require('webpack')
const config = require('../config')
const merge = require('webpack-merge')
const path = require('path')
const baseWebpackConfig = require('./webpack.base.conf')
const CopyWebpackPlugin = require('copy-webpack-plugin')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const FriendlyErrorsPlugin = require('friendly-errors-webpack-plugin')
const portfinder = require('portfinder')
var vConsolePlugin = require('vconsole-webpack-plugin'); 

const HOST = process.env.HOST
const PORT = process.env.PORT && Number(process.env.PORT)

const devWebpackConfig = merge(baseWebpackConfig, {
  module: {
    rules: utils.styleLoaders({ sourceMap: config.dev.cssSourceMap, usePostCSS: true })
  },
  // cheap-module-eval-source-map is faster for development
  devtool: config.dev.devtool,

  // these devServer options should be customized in /config/index.js
  devServer: {
    clientLogLevel: 'warning',
    historyApiFallback: {
      rewrites: [
        { from: /.*/, to: path.posix.join(config.dev.assetsPublicPath, 'index.html') },
      ],
    },
    hot: true,
    contentBase: false, // since we use CopyWebpackPlugin.
    compress: true,
    host: HOST || config.dev.host,
    port: PORT || config.dev.port,
    open: config.dev.autoOpenBrowser,
    overlay: config.dev.errorOverlay
      ? { warnings: false, errors: true }
      : false,
    publicPath: config.dev.assetsPublicPath,
    proxy: config.dev.proxyTable,
    quiet: true, // necessary for FriendlyErrorsPlugin
    watchOptions: {
      poll: config.dev.poll,
    }
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': require('../config/dev.env')
    }),
    new vConsolePlugin({
      filter: [],  // 需要过滤的入口文件
      enable: true // 发布代码前记得改回 false
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(), // HMR shows correct file names in console on update.
    new webpack.NoEmitOnErrorsPlugin(),
    // https://github.com/ampedandwired/html-webpack-plugin
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: 'index.html',
      inject: true
    }),
    // copy custom static assets
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../static'),
        to: config.dev.assetsSubDirectory,
        ignore: ['.*']
      }
    ])
  ]
})

module.exports = new Promise((resolve, reject) => {
  portfinder.basePort = process.env.PORT || config.dev.port
  portfinder.getPort((err, port) => {
    if (err) {
      reject(err)
    } else {
      // publish the new Port, necessary for e2e tests
      process.env.PORT = port
      // add port to devServer config
      devWebpackConfig.devServer.port = port

      // Add FriendlyErrorsPlugin
      devWebpackConfig.plugins.push(new FriendlyErrorsPlugin({
        compilationSuccessInfo: {
          messages: [`Your application is running here: http://${devWebpackConfig.devServer.host}:${port}`],
        },
        onErrors: config.dev.notifyOnErrors
        ? utils.createNotifierCallback()
        : undefined
      }))

      resolve(devWebpackConfig)
    }
  })
})

**Comment by diamont1001** [comment]
@SilasDong 你提供的这份配置看不出来什么问题，建议可以到项目代码里修改下本插件的代码，把 `console.log(entry);` 这句打开，再编辑一次项目代码看看输出是什么，具体路径大概如下：`node_modules/vconsole-webpack-plugin/index.js` 第 65 行

**Comment by SilasDong** [comment]
谢谢  ，我直接换成了
```js
//main.js
if (process.env.NODE_ENV === 'development') {
  var VConsole = require('vconsole/dist/vconsole.min.js')
  // eslint-disable-next-line
  var vConsole = new VConsole()
}
```

**Comment by diamont1001** [comment]
嗯嗯，这样也行的
