### ISSUE TITLE
我该如何填写filter里面的内容

### ISSUE THREAD

**Issue by tuvs85** [diamont1001/vconsole-webpack-plugin#41]
我在项目上需要设置排除一个页面不增加vconsole，我需要如何在filter里面填写配置呢

**Comment by diamont1001** [comment]
[demo](https://github.com/diamont1001/vconsole-webpack-plugin/tree/master/demo/webpack4) 和文档里都有说明呢！

filter 一般不用配置，如果某些文件你不想要添加 vconsole 的话，才需要添加到 filter 里去

**Comment by diamont1001** [comment]
filter 里是要放入口文件：
```
filter: [],  // 需要过滤的入口文件
```
