### ISSUE TITLE
Can not use vConsole plugin with this plugin

### ISSUE THREAD

**Issue by Zippowxk** [diamont1001/vconsole-webpack-plugin#47]
Cannot use vConsole plugin with this plugin

**Comment by diamont1001** [comment]
can you show your simple code?

package.json & webpack.conf.js

**Comment by Zippowxk** [comment]
How to use a plugin of vConsole with this plugin

**Comment by diamont1001** [comment]
https://github.com/diamont1001/vconsole-webpack-plugin/blob/master/README.md#%E4%BD%BF%E7%94%A8

or you can find a way in [demo](https://github.com/diamont1001/vconsole-webpack-plugin/tree/master/demo/webpack4)

**Comment by diamont1001** [comment]
simple way:

1. install: `npm install vconsole-webpack-plugin --save-dev`
2. config in `webpack.conf.js`：

webpack.conf.js

```js
var vConsolePlugin = require('vconsole-webpack-plugin'); 

module.exports = {
    ...

    plugins: [
        new vConsolePlugin({
            enable: true
        }),
        ...
    ]
    ...
}
```

**Comment by Zippowxk** [comment]
new vConsolePlugin() need a 'plugins' option to install a plugin of vConsole

**Comment by diamont1001** [comment]
> new vConsolePlugin() need a 'plugins' option to install a plugin of vConsole

just `new vConsolePlugin({enable: true}),`

**Comment by Zippowxk** [comment]
How to install this [plugin](https://github.com/smackgg/vConsole-Stats) by this webpack plugin

**Comment by diamont1001** [comment]
oh, i got what you mean. but the plugin is not included in vConsolePlugin.

vConsolePlugin will create a  vConsole for you.

and then you can install it by yourself:

```
npm install vconsole-stats-plugin -S
```

creat plugin in which page you want:

for example `index.js`：

```
const plugin = new VConsoleStatsPlugin(vConsole);
```

**Comment by diamont1001** [comment]
but honestly, i think there is no need to do that.

Stats info you can just see it in PC browser. i mean there is no need to see stats in a mobile browser.

**Comment by weivea** [comment]
> How to install this [plugin](https://github.com/smackgg/vConsole-Stats) by this webpack plugin

```
let a = new vConsole.constructor.VConsolePlugin("A","A")
a.on('renderTab', (callback) => { let html = '<div>AA</div>';callback(html); });
a.on('init', function() {
	console.log('My plugin init');
});
vConsole.addPlugin(a)
```
@Zippowxk 

```javascript
window.VConsole = vConsole.constructor;
const plugin = new VConsoleStatsPlugin(vConsole);
```

**Comment by Zippowxk** [comment]
thx
