### ISSUE TITLE
ios 10.2 会导致白屏

### ISSUE THREAD

**Issue by linxiaobiao** [diamont1001/vconsole-webpack-plugin#48]
vue-cli3 vue.config.js:  
```javascript
configureWebpack: config => {

    const tmp = {
      plugins: []
    }

    // 引入vconsole
    tmp.plugins.push(new VConsolePlugin({ enable: true }))

    return tmp
  },
```

在ios10.2中发现白屏

**Comment by linxiaobiao** [comment]
定位到走到new vconsole 会直接报TypeError: Invalid attempt to destructure non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method，建议先加个try catch 作为兜底

**Comment by diamont1001** [comment]
非常感谢

**Comment by plainnany** [comment]
似乎是vconsole导致的, https://github.com/Tencent/vConsole/releases/tag/v3.14.4

**Comment by diamont1001** [comment]
#102
