### ISSUE TITLE
[vconsole-webpack-plugin] 暂不支持 entry 为 string 类型的情况

### ISSUE THREAD

**Issue by slogan999** [diamont1001/vconsole-webpack-plugin#59]
添加了配置，但是运行webpack，出现以下问题，vconsole按钮并没有显示
![image](https://user-images.githubusercontent.com/62794506/119130502-e79c1e00-ba6a-11eb-8496-805612c45dfd.png)
暂不支持 entry 为 string 类型的情况，具体是指啥，什么情况下会出现这个问题呢

**Comment by diamont1001** [comment]
entry:[] 或者 entry:{}都可以，但不可以 entry: index.js
