### ISSUE TITLE
node v16.14.0版本插件异常，module.parent属性已经废弃

### ISSUE THREAD

**Issue by pkuyjc** [diamont1001/vconsole-webpack-plugin#77]
TypeError: Cannot read properties of undefined (reading 'paths')

**Comment by diamont1001** [comment]
应该不是因为这个原因，`module.parent` 是已经废弃，但是还可以访问。
我这边使用 [https://github.com/diamont1001/webpack-demo](https://github.com/diamont1001/webpack-demo) 测试了下 node v16.14.0 是没问题的。
你是不是使用了 `import` 引入了？
你那边可以提供个最小可复现例子吗，谢谢！
