### ISSUE TITLE
vConsole在react-router4下错误

### ISSUE THREAD

**Issue by yuanzhhh** [diamont1001/vconsole-webpack-plugin#8]
我遇到的问题是 vConsole 在 react-router4 下会导致浏览器崩溃，cpu猛涨

**Comment by diamont1001** [comment]
可以提供『最小可复现』代码吗，谢谢

**Comment by yuanzhhh** [comment]
@diamont1001 
代码涉及可能有点大，具体操作是我在开发模式下，用了react-hot-loader，在引用了vconsole-webpack-plugin在webpak当中后，在页面做一个最简单的路由跳转（react-router4），切换路由是没有问题的，但如果重复点击我当前的路由路径，则浏览器就崩掉了，cpu飙升严重

**Comment by yuanzhhh** [comment]
@diamont1001 100%复现，如果单纯在代码中使用vconsole引入是没问题的

**Comment by diamont1001** [comment]
@yuanzhhh 把 webpack 的入口配置发来看看，我有空看下

**Comment by diamont1001** [comment]
![image](https://user-images.githubusercontent.com/7159888/34705509-d50bb11c-f53b-11e7-85a4-f1bf20e60b68.png)

参考这个图，看下是不是因为自己的 react router 文件无限循环了

**Comment by yuanzhhh** [comment]
死循环应该不会，这样用不用 vconsole-webpack-plugin 堆栈肯定都会满，我将 vconsole-webpack-plugin 去掉，重复动作就没有再复现。单独使用的 vconsole 这个库引入，这个问题是没有发生的

**Comment by diamont1001** [comment]
不好意思，我今天试一下是没问题的喔，确定了不是 react-router@4 的问题

具体可以拿这个 demo 来试下，我试了没问题：[https://github.com/diamont1001/react-router-dom-demo](https://github.com/diamont1001/react-router-dom-demo)

所以，你那边如果还有问题的话，希望可以提供个「最小可复现代码」，或者提个 PR，谢谢！
