### ISSUE TITLE
vue开发h5，接口输出大文件流会导致卡死，且在ios端打开无法切换tab

### ISSUE THREAD

**Issue by Leo-bai94** [diamont1001/vconsole-webpack-plugin#89]
vue2.x开发的h5页面中，打印大文件流或者接口返回有大文件流会导致vconsole卡死，以及页面卡死，无法关闭vconsole，页面也无法点击滑动；另外在ios端会出现切换tab时无法切换，且自动打印出日志的情况

**Comment by diamont1001** [comment]
vconsole 3.14.4已解决该问题，本插件 1.8.0 已将 vconsole 升级到 `3.15`。

参考：[https://github.com/Tencent/vConsole/blob/dev/CHANGELOG.md#3144-2022-03-31](https://github.com/Tencent/vConsole/blob/dev/CHANGELOG.md#3144-2022-03-31)
